CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(64) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY email (email)
) CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE users_validation (
  id VARCHAR(32) PRIMARY KEY,
  userId INT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY userId (userId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) CHARACTER SET utf8 COLLATE utf8_general_ci;
